version: "3.9"

services:
  api:
    container_name: api
    build: ./plugin-store-api
    ports:
      - "5100:3000"
    depends_on:
      - db
      - wpdb
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=qwerty123
      - DB_NAME=plugin-store
      - WP_DB_HOST=wpdb
      - WP_DB_PORT=3306
      - WP_DB_USER=wpuser
      - WP_DB_PASS=qwerty123
      - WP_DB_NAME=wordpressdb
      - JWT_SECRET=vZiXOo3r7IgFtLh3TVtuiKxVtXfqMlAs
      - LICENSE_URL=http://192.168.10.46:10100
      - WOOCOMMERCE_API_URL=https://dev-shop.db.timal.kz
      - WOOCOMMERCE_CK=ck_4e54f68495be25e0d650b4d1c13b3973ef557cf7
      - WOOCOMMERCE_CS=cs_96dfcc7ce2c979c57b0aefc426d14938f40ffc12

  db:
    container_name: postgres
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "plugin-store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
