version: "3.9"

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
  
  wordpress:
    container_name: wordpress
    image: mailpoet/wordpress:wp-6.1_php8.1_20201122.1
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: qwerty123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./wordpress:/var/www/html
      - ./restly:/var/www/html/wp-content/themes/restly
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - wpdb

  wpdb:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: qwerty123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./wpdb:/var/lib/mysql
