version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "plugin-store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
  
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: qwerty123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  wpdb:
    container_name: mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: qwerty123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wpdb:/var/lib/mysql
  
volumes:
  db:
  wordpress:
  wpdb:
