version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - "5100:3000"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "plugin-store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
  
volumes:
  db: